# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9277cfcf7c21c5f18dcfe0cc570239f52e58d5c6cee62083331100e0171c020f153be20d9587d9ddce71c56f8f6b6313b97a860f3ba4044dd3786a48300ec67e

test:
  secret_key_base: caf11d29587500df7129b3baeb852516ca29b0a572b6f11895c2fb0001c27b2431462048d0926aae942ebfe9801b77b56e5ddf917cec6d62f5e653d88107eb10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
